# ServiceAccounts for central-analytics namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: central-postgres-sa
  namespace: central-analytics
  labels:
    app.kubernetes.io/part-of: hls-demo
    app.kubernetes.io/component: central-db
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etl-job-sa
  namespace: central-analytics
  labels:
    app.kubernetes.io/part-of: hls-demo
    app.kubernetes.io/component: etl
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-analytics-sa
  namespace: central-analytics
  labels:
    app.kubernetes.io/part-of: hls-demo
    app.kubernetes.io/component: analytics
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: report-viewer-sa
  namespace: central-analytics
  labels:
    app.kubernetes.io/part-of: hls-demo
    app.kubernetes.io/component: viewer
